# This uses newer and faster docker based build system
language: php

services:
  - mysql

php:
  - nightly # PHP 7.0
  - 7.1
  - 5.6
  - 7.3
  - 7.2

#notifications:
#  on_success: never
#  on_failure: change


env:
  - WP_VERSION=master WP_MULTISITE=0
  - WP_VERSION=5.3.2.1 WP_MULTISITE=0
#  - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test

matrix:
  allow_failures:
    - php: nightly

before_script:
  # Install composer packages before trying to activate themes or plugins
  # - composer install

#  - git clone https://github.com/Koodimonni/wordpress-test-template wp-tests
#  - bash wp-tests/bin/install-wp-tests.sh test root '' localhost $WP_VERSION
  - wget https://raw.github.com/benbalter/wordpress-plugin-tests/setup/setup.sh
  - source setup.sh
script:
#  - phpcs --standard=WordPress ./**/*.php
  - phpunit
#  - cd tests/spec && bundle exec rspec test.rb
# wordpress-plugin-tests specific config
# Tells Travis CI not to run unit tests against the setup branch
branches:
  except:
    - setup